### ISSUE TITLE
Reject filters not ending in :d

### ISSUE THREAD

**Issue by da2x** [innix/shrek#2]
`d` must be the last character in an v3 address. The CLI should warn and reject filters for `:end` that doesn’t end with `d`.

**Comment by innix** [comment]
You are right, thanks for raising this issue.

It's also true that the 2nd last character in a v3 address must be one of these characters: `a`, `i`, `q`, `y`. So for example, every valid v3 address will have one of these endings:

```
ad.onion
id.onion
qd.onion
yd.onion
```

The filter validation function is very basic, it could definitely do with some improvements:

https://github.com/innix/shrek/blob/0d771d3381b28904c2da63ce2bea38ea09eb7127/cmd/shrek/main.go#L222-L224

**Comment by innix** [comment]
This has been fixed as part of the [v0.6.1](https://github.com/innix/shrek/releases/tag/v0.6.1) release (76baa6a86c8eb5e39ad4ea68eeb4b7efa044d3a1).
